import { chromium } from "playwright";
import http from "node:http"; import fs from "node:fs"; import path from "node:path";
const root = path.dirname(new URL(import.meta.url).pathname);
const srv = http.createServer((q, r) => { const f = path.join(root, decodeURIComponent(q.url.split("?")[0])); fs.readFile(f, (e, d) => { if (e) { r.writeHead(404); r.end(); return; } r.writeHead(200, { "content-type": f.endsWith(".js") ? "text/javascript" : "text/html" }); r.end(d); }); }).listen(8765);
const [,, out = "out.png", w = "1600", h = "900", qs = ""] = process.argv;
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const p = await b.newPage({ viewport: { width: +w, height: +h } });
p.on("console", (m) => console.log("console:", m.text().slice(0, 300)));
p.on("pageerror", (e) => { console.log("pageerror:", e.message); process.exit(1); });
await p.goto(`http://localhost:8765/render.html?w=${w}&h=${h}&${qs}`);
await p.waitForFunction(() => window.__done === true, null, { timeout: 600000 });
await p.screenshot({ path: out });
await b.close(); srv.close();
