// Generated by scripts/gen-photos.ts — do not edit by hand.
// Keys are `${listingId}-${index}` (or extras like `upload-0`, `auth`). Photos live in /public/photos/<key>.jpg
export const PHOTO_KEYS: string[] = [];
